name: Regression E2E
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
       uses: actions/setup-node@v3
       # install npm dependencies, cache them correctly
       # and run all cypress tests 
      - name: cypress run
        uses: cypress-io/github-action@v5
